#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot

set -eu #-x for verbose logging to juju debug-log

juju-log 'Reading your config.yaml file...'
pod_url=`config-get pod_url`

apt-get -y install -q ruby1.9.1-dev
REALLY_GEM_UPDATE_SYSTEM=true gem update --system

juju-log 'Installing Required packages...'
apt-get -y install -q libmysqlclient16 libmysqlclient16-dev\
			imagemagick libmagick9-dev git-core\
			build-essential libxslt1.1 libxslt1-dev libxml2
gem install bundler

juju-log 'Getting Diaspora from git repository...'
## TODO: Should verify build-status before getting
cd ~
git clone https://github.com/diaspora/diaspora.git
juju-log 'Installing required Ruby gems...'
cd diaspora
export DB="mysql"
bundle install --without development:test:heroku --path vendor/bundle --binstubs bin/ --deployment

juju-log 'Configuring your pod...'
cp config/application.yml.example config/application.yml
cp config/database.yml.example config/database.yml
sed -i 's/rails_env: "development"/rails_env: "production"/' config/script_server.yml
sed -i 's/serve_static_assets = false/serve_static_assets = true/' config/environments/production.rb

# injecting settings to application.yml
sed -i "s/pod_url: \"http:\/\/localhost:3000\/\"/pod_url: \"\"/"
cat > "config/application.yml" <<EOS
production:
  pod_url: "${pod_url}"
  ca_file: '/etc/ssl/certs/ca-certificates.crt'
  redis_url: ''
  s3_key: 'key'
  s3_secret: 'secret'
  s3_bucket: 'my_photos'
  s3_region: 'us-east-1'
  registrations_closed: false
  open_invitations: true
  admin_account: ''
  invite_count: 25
  no_follow_diasporahq: false
  community_spotlight:
    - 'diasporahq@joindiaspora.com'
  spotlight_suggest_email: ''
  admins:
    - 'example_user1dsioaioedfhgoiesajdigtoearogjaidofgjo'
  mount_resque_web: true
  debug: false
  airbrake_api_key: ''
  facebook_app_id: ''
  facebook_app_secret: ''
  twitter_consumer_key: ''
  twitter_consumer_secret: ''
  tumblr_consumer_key: ''
  tumblr_consumer_secret: ''
  NEW_RELIC_LICENSE_KEY: ''
  new_relic_app_name: ''
  single_process_mode: false
  pubsub_server: 'https://pubsubhubbub.appspot.com/'
  mailer_on: false
  smtp_address: 'smtp.example.com'
  smtp_port: '587'
  mailer_method: 'smtp'
  message_bus_api_key: ''
  smtp_authentication: 'plain'
  smtp_starttls_auto: true
  smtp_openssl_verify_mode:
  smtp_domain: 'example.com'
  smtp_username: 'smtp_username'
  smtp_password: 'secret'
  smtp_sender_address: 'no-reply@joindiaspora.com'
  circumvent_ssl_requirement: false
  image_redirect_url: ''
  google_a_site: false
  piwik_id:
  piwik_url:

  # Donations

  # Leave this blank to not show the request for donations
  # Use paypal for recurring donations
  paypal_hosted_button_id: ""
EOS

## TODO: other config stuff
