#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot

set -eu #-x for verbose logging to juju debug-log

juju-log 'Reading your config.yaml file...'
pod_url=`config-get pod_url`

apt-get -y install -q ruby1.9.1-dev
REALLY_GEM_UPDATE_SYSTEM=true gem update --system

juju-log 'Installing Required packages...'
apt-get -y install -q libmysqlclient16 libmysqlclient16-dev\
			imagemagick libmagick9-dev git-core\
			build-essential libxslt1.1 libxslt1-dev libxml2
gem install bundler

juju-log 'Getting Diaspora from git repository...'
## TODO: Should verify build-status before getting
cd ~
git clone https://github.com/diaspora/diaspora.git
juju-log 'Installing required Ruby gems...'
cd diaspora
export DB="mysql"
bundle install --without development:test:heroku --path vendor/bundle --binstubs bin/ --deployment

juju-log 'Configuring your pod...'
cp config/application.yml.example config/application.yml
cp config/database.yml.example config/database.yml
sed -i 's/rails_env: "development"/rails_env: "production"/' config/script_server.yml
sed -i 's/serve_static_assets = false/serve_static_assets = true/' config/environments/production.rb
# injecting settings to application.yml
## TODO: other config stuff
